### ISSUE TITLE
Error when using Norminette command

### ISSUE THREAD

**Issue by shimmi134** [MrSloth-dev/NorminetteDiagnostics#2]
![image](https://github.com/user-attachments/assets/117016dc-bfca-431a-9c0c-948215a7930e)
Whenever calling the command ```:Normiette``` there is an error because it tries to execute ```run_normiette_check``` without any parameters. I belive it should be the same function as the keybind, ```toggle_norminette```.

**Comment by MrSloth-dev** [comment]
Already pushed a change in this [commit](https://github.com/MrSloth-dev/42-NorminetteNvim/commit/d39952f51a2c7a1eb821697859ca25d65ca7770d)  Please Check if it's working now. This bug went overlooked because it's better to use the keybing <leader>n. Thank You for noticing this!

**Comment by shimmi134** [comment]
Yes, it's working now. Thanks for your work!
